apiVersion: apps/v1
kind: Deployment
metadata:
  name: root
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: root
  template:
    metadata:
      labels:
        app: root
    spec:
      containers:
        - name: root-service
          image: root-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: conf-root